#!/usr/bin/env python3
"""dic2c: a compiled DECtalk dictionary (dtalk_us.dic, the format dic.c writes and the
Linux build loads) -> main_dict[] as C, in the CHEESY_DICT_COMPRESSION layout that the
ARM7 configuration's TextToSpeechInit reads:

    U32 entries, U32 data bytes, U32 fc_entries, U32 fc_table[fc_entries],
    U32 index[entries], data: per entry  fc_table index (1 byte), text NUL, phonemes NUL
    (no padding)

The .dic file has the same index + data, but each entry starts with its full 4-byte
form class. The upstream lts/maindict_us.c is a 4809-word subset in this layout; this
gives the ARM7 build the full dictionary the Linux build uses.

    dic2c.py dtalk_us.dic maindict_full.c
"""
import struct
import sys


def convert(dic):
    entries, nbytes = struct.unpack_from("<II", dic, 0)
    index = struct.unpack_from("<%dI" % entries, dic, 8)
    data = dic[8 + 4 * entries:]
    if len(data) != nbytes:
        sys.exit("dic2c: %d data bytes, header says %d" % (len(data), nbytes))
    ends = sorted(index[1:]) + [nbytes]
    if list(index) != sorted(index):
        sys.exit("dic2c: index is not in data order")
    fcs = sorted({struct.unpack_from("<I", data, off)[0] for off in index})
    if len(fcs) > 256:
        sys.exit("dic2c: %d form classes do not fit in one byte" % len(fcs))
    fc_slot = {fc: i for i, fc in enumerate(fcs)}
    out_index, out_data = [], bytearray()
    for off, end in zip(index, ends):
        # text NUL phonemes NUL; the rest up to the next entry is the .dic
        # file's 4-byte alignment padding, which the compressed layout drops
        text_end = data.index(b"\0", off + 4, end)
        phon_end = data.index(b"\0", text_end + 1, end)
        out_index.append(len(out_data))
        out_data.append(fc_slot[struct.unpack_from("<I", data, off)[0]])
        out_data += data[off + 4:phon_end + 1]
    return (struct.pack("<III", entries, len(out_data), len(fcs))
            + struct.pack("<%dI" % len(fcs), *fcs)
            + struct.pack("<%dI" % entries, *out_index)
            + bytes(out_data))


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: dic2c.py dtalk_us.dic out.c")
    blob = convert(open(sys.argv[1], "rb").read())
    with open(sys.argv[2], "w") as f:
        f.write("/* Generated by dic2c.py from %s; do not edit. */\n" % sys.argv[1].split("/")[-1])
        f.write("const unsigned char main_dict[%d] = {\n" % len(blob))
        for i in range(0, len(blob), 16):
            f.write(",".join("%d" % b for b in blob[i:i + 16]) + ",\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
